FROM node:16.16.0 as build

WORKDIR /app

COPY . .

RUN npm i

ENV PORT=80

ENV ENDPOINT="http://localhost:9000/api"

RUN npm run build

FROM nginx:1.21.1-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80