services:
    backend_prod:
        container_name: backend_prod
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        ports:
            - 9000:9000
        environment:
            - APPID=${APPID}

    frontend_prod:
        container_name: frontend_prod
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        environment:
            - ENDPOINT="http://localhost:9000/api"
            - PORT=80
