services:
    weatherapp_backend:
        container_name: weatherapp_backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./backend:/app

    weatherapp_frontend:
        container_name: weatherapp_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./frontend:/app
