services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        environment:
            - APPID=${APPID}

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
