services:
    backend:
        container_name: backend_dev
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./backend:/app
        environment:
            - APPID=${APPID}

    frontend:
        container_name: frontend_dev
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./frontend:/app
