- name: Install Docker on Ubuntu
  hosts: aws-ec2
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Add current user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Give Docker compose permissions
      file:
        path: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
